create table public.wishes (
    id bigint generated by default as identity primary key,
    message text not null check (char_length(trim(message)) > 0),
    created_at timestamptz not null default now()
);

alter table public.wishes enable row level security;
